language: node_js
node_js:
- 6
notifications:
  slack:
    secure: SAJhyZg+pG+oBGOhL5pSQ3KeMZfevtl/A73XVygsd/OFGlPOB3GbziiqU1bLo21zP+FIC04nRJyRNatjvcWJqSvRRgBV9Kgqsz47konPRLB0xO8kLfXxVSNLVWPTe/Vw4H1lHQSalY9ayYKIiQXCfYWdlONZ2OIm8Fnb15GXNGCtLNmdXlPVoPcQezffhtwrS8dKYaINVClDJ2WeUDmBh7fx0SDuKDetXi6+nIKjTIvR2/veieZltimJQy5l9G0tp15dmorF+jVe+k3Sqi9yvvfJK24yeArmEujj99bt7vO+hpnkQSG/DQtApN0nczrc1VMiktXyVENdcST+de/i+xJAYggE3Me1US/iGGPCAkMIz+5NaeGs2lDxYZh1GbAmHkXjZlAGWgA1bnHFmrFIb40eVNq+8h4Tvm+EM9bFCC1c3x6kcBwQchi01o0FwX3V58jnNUvnFMYCF8CCXPnzHIAbYHZ25nkgPwJQBkytzABkTLyFZBQTy5snYBlpTgRZXsrvyxIL6pWvsdKw/96tD8RayTQIT0fGkNoMaxBf9L0CYxKoHNA1iginYgDdTXK9oMOSMtc2vslKnIchjDerMjiH3gN2DfNsRzBaK0WZ8Y1SznzVaUKCvohTW/CPuGCYw+SFnJozyTO72X+8E7Vht9aUsy3sO5ubZTf5PYPXXyc=
